# Generated by Django 6.0.8 on 2026-09-23 04:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duo", "0001_initial"),
        ("tap_grid", "0005_entity_natural_key_clear"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="duoaccount",
            name="edition",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="duoaccount",
            name="helpdesk_bypass",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="duoaccount",
            name="inactive_user_expiration",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="duoaccount",
            name="lockout_threshold",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalduoaccount",
            name="edition",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="historicalduoaccount",
            name="helpdesk_bypass",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="historicalduoaccount",
            name="inactive_user_expiration",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalduoaccount",
            name="lockout_threshold",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="DuoAdministrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "admin_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                ("role", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "restricted_by_admin_units",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_administrator",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuoApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "integration_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "integration_type",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "user_access",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "adminapi_permissions",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "self_service_allowed",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_application",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuoBypassCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "bypass_code_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("expires", models.BooleanField(blank=True, default=None, null=True)),
                ("expiration", models.DateTimeField(blank=True, null=True)),
                (
                    "reuse_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "admin_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_bypass_code",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuoEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "epkey",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "endpoint_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("os_family", models.CharField(blank=True, default="", max_length=255)),
                (
                    "os_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("model", models.CharField(blank=True, default="", max_length=255)),
                (
                    "trusted_endpoint",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "disk_encryption_status",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "firewall_status",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "password_status",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "health_app_client_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "health_data_last_collected",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_endpoint",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuoGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "group_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(blank=True, default="", max_length=16)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_group",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuoHardwareToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "token_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("serial", models.CharField(blank=True, default="", max_length=255)),
                ("token_type", models.CharField(blank=True, default="", max_length=8)),
                ("totp_step", models.IntegerField(blank=True, default=None, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_hardware_token",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuoPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "phone_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("platform", models.CharField(blank=True, default="", max_length=255)),
                ("phone_type", models.CharField(blank=True, default="", max_length=16)),
                ("model", models.CharField(blank=True, default="", max_length=255)),
                ("capabilities", models.JSONField(blank=True, default=None, null=True)),
                ("activated", models.BooleanField(blank=True, default=None, null=True)),
                ("encrypted", models.CharField(blank=True, default="", max_length=255)),
                (
                    "fingerprint",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "screenlock",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tampered", models.CharField(blank=True, default="", max_length=255)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_phone",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuoPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "policy_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("is_global", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "new_user_behavior",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "allowed_auth_methods",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("sections", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_policy",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuoUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "username",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("realname", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "is_enrolled",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("last_directory_sync", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_user",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuoWebauthnCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "webauthnkey",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "credential_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("date_added", models.DateTimeField(blank=True, null=True)),
                ("date_last_used", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "duo__duo_webauthn_credential",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalDuoAdministrator",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "admin_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                ("role", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "restricted_by_admin_units",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo administrator",
                "verbose_name_plural": "historical duo administrators",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuoApplication",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "integration_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "integration_type",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "user_access",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "adminapi_permissions",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "self_service_allowed",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo application",
                "verbose_name_plural": "historical duo applications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuoBypassCode",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "bypass_code_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("expires", models.BooleanField(blank=True, default=None, null=True)),
                ("expiration", models.DateTimeField(blank=True, null=True)),
                (
                    "reuse_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "admin_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo bypass code",
                "verbose_name_plural": "historical duo bypass codes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuoEndpoint",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "epkey",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "endpoint_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("os_family", models.CharField(blank=True, default="", max_length=255)),
                (
                    "os_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("model", models.CharField(blank=True, default="", max_length=255)),
                (
                    "trusted_endpoint",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "disk_encryption_status",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "firewall_status",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "password_status",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "health_app_client_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "health_data_last_collected",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo endpoint",
                "verbose_name_plural": "historical duo endpoints",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuoGroup",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "group_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(blank=True, default="", max_length=16)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo group",
                "verbose_name_plural": "historical duo groups",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuoHardwareToken",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "token_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("serial", models.CharField(blank=True, default="", max_length=255)),
                ("token_type", models.CharField(blank=True, default="", max_length=8)),
                ("totp_step", models.IntegerField(blank=True, default=None, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo hardware token",
                "verbose_name_plural": "historical duo hardware tokens",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuoPhone",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "phone_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("platform", models.CharField(blank=True, default="", max_length=255)),
                ("phone_type", models.CharField(blank=True, default="", max_length=16)),
                ("model", models.CharField(blank=True, default="", max_length=255)),
                ("capabilities", models.JSONField(blank=True, default=None, null=True)),
                ("activated", models.BooleanField(blank=True, default=None, null=True)),
                ("encrypted", models.CharField(blank=True, default="", max_length=255)),
                (
                    "fingerprint",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "screenlock",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tampered", models.CharField(blank=True, default="", max_length=255)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo phone",
                "verbose_name_plural": "historical duo phones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuoPolicy",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "policy_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("is_global", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "new_user_behavior",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "allowed_auth_methods",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("sections", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo policy",
                "verbose_name_plural": "historical duo policys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuoUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "username",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("realname", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "is_enrolled",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("last_directory_sync", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo user",
                "verbose_name_plural": "historical duo users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuoWebauthnCredential",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "webauthnkey",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "credential_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("date_added", models.DateTimeField(blank=True, null=True)),
                ("date_last_used", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duo webauthn credential",
                "verbose_name_plural": "historical duo webauthn credentials",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
