# Generated by Django 6.0.8 on 2026-09-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("duo", "0002_duo_corpus_v1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="duoaccount",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicalduoaccount",
            name="configuration",
        ),
    ]
