# Generated by Django 6.0.8 on 2026-09-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0003_drop_unused_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duoaccount',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duoadministrator',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duoapplication',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duobypasscode',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duoendpoint',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duogroup',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duohardwaretoken',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duophone',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duopolicy',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duouser',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='duowebauthncredential',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduoaccount',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduoadministrator',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduoapplication',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduobypasscode',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduoendpoint',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduogroup',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduohardwaretoken',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduophone',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduopolicy',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduouser',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalduowebauthncredential',
            name='tags',
        ),
        migrations.AddField(
            model_name='duoapplication',
            name='account_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='duogroup',
            name='account_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='duopolicy',
            name='account_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalduoapplication',
            name='account_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalduogroup',
            name='account_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalduopolicy',
            name='account_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='duoapplication',
            index=models.Index(fields=['account_name', 'name'], name='nk_duo__duo_application'),
        ),
        migrations.AddIndex(
            model_name='duogroup',
            index=models.Index(fields=['account_name', 'name'], name='nk_duo__duo_group'),
        ),
        migrations.AddIndex(
            model_name='duopolicy',
            index=models.Index(fields=['account_name', 'name'], name='nk_duo__duo_policy'),
        ),
    ]
